### PR TITLE
Third trys the charm

### PR DESCRIPTION
**Pull request by ThomasFHoy**
added post and tried to embed video

### CODE REVIEW

**Comment by ThomasFHoy** [comment]
Need to update index page

**Comment by neilmispelaar** [comment]
Yes you are correct

**Comment by ThomasFHoy** [comment]
@FarwaFF Are we good to go live with this?:https://deploy-preview-3--toadforca.netlify.app/blog/get-to-know-us.html

**Comment by ThomasFHoy** [comment]
oops noticing a typo

**Pull request merged**
